config/routes.rb
DiscussionBoard::Application.routes.draw do

  controller :helps do
    get :introduction
  end

  resources :speaks, except: :destroy do
    post :vote, on: :member
  end

  resources :users, except: [:destroy]

  resource :session, only: [:new, :create, :destroy]
  match "sessions/destroy"

  namespace :admin do
    resources :users
    resource :configurable
    get "speaks/download_all"
  end

  root to: redirect("/speaks")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :access, :helps
    can :read, :speaks
    can :access, :users
    can :access, :sessions
    if user
      case user.role.to_sym
      when :admin
        can [:create, :update], :speaks, user_id: user.id
        can :access, :all
      when :attendee
        can :vote, :speaks
        can [:create], :speaks, user_id: user.id unless Configurable.stop_speaking
        can [:update], :speaks do |s|
          s.user_id == user.id && 1.minutes.ago < s.created_at
        end
        can [:create, :update], :users, id: user.id
      else
        #can [:vote], :speaks, user_id: user.id
      end
    end
  end
end

app/models/auth.rb
class Auth < ActiveRecord::Base
  belongs_to :user
  attr_accessible :omni_hash, :provider, :uid
end

app/models/speak.rb
class Speak < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  validates :text, length: 3..Configurable.speak_length
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_voter
  ROLES = %w(admin attendee none)

  validates :username, uniqueness: true, allow_nil: true
  validates :nickname, length:{ in: 2..10 }
  validates :password, :presence => true, length: 6..40, :on => :create
  validates_confirmation_of :password

  def role
    super.presence || 'none'
  end
  def display_name
    nickname.presence || "匿名_#{username}"
  end
end

app/controllers/admin/configurables_controller.rb
class Admin::ConfigurablesController < ApplicationController
  include ConfigurableEngine::ConfigurablesController
end

app/controllers/admin/speaks_controller.rb
class Admin::SpeaksController < ApplicationController
  def download_all
    rows = []
    Speak.find_each do |speak|
      rows << [speak.id, speak.created_at, speak.text].join(",")
    end
    render text: rows.join("\n")
  end
end

app/controllers/admin/users_controller.rb
# coding: utf-8

class Admin::UsersController < ApplicationController
  permits :spam
  load_and_authorize_resource

  # GET /users
  def index
  end

  # GET /users/1
  def show(id)
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit(id)
  end

  # POST /users
  def create
    users = params[:users]
    count = 0
    users.split(/\n/).each do |line|
      username, password = line.split(/,/)
      User.create!(username: username, nickname: "匿名_#{username}", password: password.chomp, role: :attendee)
      count += 1
    end
    redirect_to admin_users_path, notice: "#{count} users were successfully created."
  end

  # PUT /users/1
  def update(id, user)
    if @user.update_attributes(user)
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy(id)
    @user.destroy

    redirect_to admin_users_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  enable_authorization
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params[:user] || {}
    login(user_params[:username], user_params[:password])
    if logged_in?
      redirect_to root_url, notice: "ログインしました。"
    else
      flash.now[:alert] = "ログインできません。"
      @user = User.new(params[:user])
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "ログアウトしました。"
  end
end

app/controllers/speaks_controller.rb
# coding: utf-8

class SpeaksController < ApplicationController
  permits :text
  load_and_authorize_resource except: :index

  # GET /speaks
  def index
    @q = Speak.includes(:user, :votes).search(params[:q])
    if params[:q]
      @q = Speak.includes(:user).search(params[:q])
      @speaks = @q.result(:distinct => true)
    elsif params[:order] == 'votes'
      @speaks = Speak.includes(:user, :votes).order('cached_votes_score DESC, created_at DESC')
      @speaks = @speaks.where("? <= id", Configurable.speak_from) if Configurable.speak_from.to_i > 0
    else
      @speaks = Speak.includes(:votes, user: :votes).order("created_at DESC")
    end
  end

  # GET /speaks/1
  def show(id)
  end

  # GET /speaks/new
  def new
  end

  # GET /speaks/1/edit
  def edit(id)
  end

  # POST /speaks
  def create(speak)
    if Speak.where(user_id: current_user.id).where("? < created_at", Configurable.speak_limit_per_minutes.minutes.ago).count > Configurable.speak_limit_counts
      return render action: :new
    end
    if @speak.save
      redirect_to speaks_path, notice: "発言しました"
    else
      render action: 'new'
    end
  end

  # PUT /speaks/1
  def update(id, speak)
    if @speak.update_attributes(speak)
      redirect_to @speak, notice: I18n.t("helpers.notices.updated", model: Speak.model_name.human)
    else
      render action: 'edit'
    end
  end

  def vote(id)
    if params[:cancel]
      current_user.unvote_for @speak
      notice = "下げました。"
    else
      current_user.upvotes @speak
      notice = "上げました。"
    end
    respond_to do |format|
      format.html { redirect_to @speak, notice: notice }
      format.js
    end
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  respond_to :html
  permits :nickname
  load_and_authorize_resource

  # GET /users/1
  def show(id)

  end

  def new
    @user.nickname = "匿名"
  end

  # GET /users/1/edit
  def edit(id)
  end

  def create(user)
    @user.password = 'abcdefghjkmnpqrtuvwxyzABCDEFGHJKLMNPQRTUVWXY346789+-=!#$%&'.chars.sample(6).join
    @user.role = :attendee
    if @user.save
      @user.update_column(:username, @user.id)
      flash.notice = "アカウントを作成しました。他の端末で同じアカウントでログインしたい方は、<a href='#{user_path(@user)}'>マイページ</a>からパスワードを設定してください。"
      auto_login(@user)
    end
    respond_with @user, location: speaks_url
  end

  # PUT /users/1
  def update(id, user)
    if @user.update_attributes(user)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy(id)
    @user.destroy

    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/speaks_helper.rb
module SpeaksHelper
  def with_speak_link(str)
    str.gsub(/#(\d+)/) do
      target = Speak.find_by_id($1)
      next $& unless target
      link_to($&, speak_path($1), title: truncate(target.text) )
    end.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for @user, url: admin_user_path(@user), :html => { :class => 'form-horizontal' } do |f|
  = f.input :spam
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:display_name)
      %th= model_class.human_attribute_name(:spam)
      %th= model_class.human_attribute_name(:role)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.display_name, user
        %td= user.spam
        %td= model_class.human_attribute_name("roles.#{user.role}")
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_user_path, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= form_tag admin_users_path do |f|
  = text_area_tag :users
  = submit_tag

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @user.display_name
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @user.role

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), root_path, :class => 'btn'

app/views/helps/introduction.html.haml
.page-header
  %h1 このシステムについて
%h2 これは何？
このシステムは、公開討議等で参加者からの発言を集約するためのディスカッションボードシステムです。
このシステムに「参加者」としてログインしたユーザーは自由に発言が出来ます。
会の運営スタッフはこれらの意見をもとに、司会進行をしてゆきます。
%h2 どんな特徴があるの？
%h3 投票システム
ログインユーザーは、任意の発言に対して同意を示すことが出来ます。
発言は投票順に並べる事が出来ます。また、その際に「発言番号○○番以降」という指定が出来ますので、会の進行にあわせて、最新の話題における人気発言を追うことが出来ます。

%h2 誰が作ったの？
会の運営スタッフの依頼により、 <a href="https://twitter.com/kuboon">大久保 康平</a> が開発しました。全てのソースコードは <a href="https://github.com/open-political-platform-japan/discussion-board">GitHub</a> にて公開しています。

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : Configurable.title
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/favicon.ico" rel="shortcut icon")


  %body{class: controller.controller_name}
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.brand(href="/")= Configurable.title
          %ul.nav
            %li= link_to "発言一覧", speaks_path
            %li= link_to "発言する", new_speak_path if can? :create, :speaks
            %li= link_to "ユーザ一覧", admin_users_path if can? :access, :admin_users
            %li= link_to "config", admin_configurable_path if can? :access, :admin_configurables
          %ul.nav.pull-right
            - if logged_in?
              %li.dropdown
                %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                  %i.icon-user.icon-white
                  = current_user.display_name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'マイページ', user_path(current_user)
                  %li= link_to 'ログアウト', sessions_destroy_path
            - else
              %li= link_to '登録', new_user_path unless Configurable.stop_speaking
              %li= link_to 'ログイン', new_session_path

            %li= link_to glyph(:question_sign), introduction_path

    .container-fluid
      .row-fluid
        .span12
          = bootstrap_flash
          - if Configurable.admin_message.present?
            .alert.alert-notice
              管理者より:
              =raw Configurable.admin_message
          = yield
    
      %footer
        %p &copy; <a href="https://twitter.com/kuboon">kuboon</a> 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-41625888-1', 'herokuapp.com');
      ga('send', 'pageview');

app/views/speaks/_form.html.haml
= simple_form_for @speak, :html => { :class => 'form-horizontal' } do |f|
  = f.input :text, input_html: {rows: 5}
  \#番号 で発言にリンクできます。
  .form-actions
    = f.submit "発言する", :class => 'btn btn-primary', data:{ disable_with: "送信中..." }
    = link_to t('.cancel', :default => t("helpers.links.cancel")), speaks_path, :class => 'btn'

app/views/speaks/_search_form.html.haml
= search_form_for @q, html: { class: 'form-search' } do |f|
  =f.text_field :text_cont, class: 'search-query', placeholder: "検索"
  =f.submit class: :btn

app/views/speaks/_speak.html.haml
%article
  %header
    = link_to speak do
      [#{speak.id}] #{time_ago_in_words speak.created_at}前
    (#{speak.user.display_name})
    %span{id: "vote_#{speak.id}"}
      = speak.cached_votes_score
      - if can? :vote, speak
        - if current_user.votes.pluck(:votable_id).include? speak.id
          = link_to glyph(:thumbs_up, :active), vote_speak_path(speak, cancel: true), method: :post, remote: true
        - else
          = link_to glyph(:thumbs_up), vote_speak_path(speak), method: :post, remote: true

    = link_to t('.edit', :default => t("helpers.links.edit")), edit_speak_path(speak), :class => 'btn btn-mini' if can? :update, speak
  %p
    = with_speak_link(speak.text)

app/views/speaks/_speaks.html.haml
- speaks = @speaks.page(params[:page]).per(50)
= paginate speaks, remote: true
= render speaks
= paginate speaks, remote: true

app/views/speaks/_vote_icon.html.haml
%span{id: "vote_#{speak.id}"}
  = speak.cached_votes_score
  - if can? :vote, speak
    - if current_user.votes.pluck(:votable_id).include? speak.id
      = link_to glyph(:thumbs_up, :active), vote_speak_path(speak, cancel: true), method: :post, remote: true
    - else
      = link_to glyph(:thumbs_up), vote_speak_path(speak), method: :post, remote: true

app/views/speaks/edit.html.haml
- model_class = Speak
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/speaks/index.html.haml
- model_class = Speak

- if can? :create, :speaks
  = form_for Speak.new, :html => { :class => 'form-horizontal' } do |f|
    \#番号 で発言にリンクできます。
    %br
    = f.text_field :text, input_html: {style: "width: 90%; height: 2em;"}
    = f.submit "発言する", :class => 'btn btn-primary', data:{ disable_with: "送信中..." }

.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
= render "search_form"
%ul.nav.nav-tabs
  %li{class: params[:order].blank? && :active}
    %a{href: speaks_path} 時間順
  %li{class: params[:order]=="votes" && :active}
    %a{href: speaks_path(order: :votes)}
      投票順
      = "(#{Configurable.speak_from}番以降)" if Configurable.speak_from.to_i > 0

= check_box_tag :auto_refresh
自動更新する
#speaks= render "speaks"

app/views/speaks/new.html.haml
- model_class = Speak
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/speaks/show.html.haml
- model_class = Speak
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = link_to @speak.user.display_name, @speak.user
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = with_speak_link(@speak.text)

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), speaks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_speak_path(@speak), :class => 'btn' if can? :edit, @speak
  = link_to t('.destroy', :default => t("helpers.links.destroy")), speak_path(@speak), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' if can? :destroy, @speak

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification
  = f.input :nickname
  = f.input :password if @user.persisted?
  = f.input :password_confirmation if @user.persisted?
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), :back, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @user.display_name
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @user.role

.form-actions
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn' if can? :update, @user
  = link_to t('.back', :default => t("helpers.links.back")), root_path, :class => 'btn'